---
title: "Exploring Spotifyr"
author: "Ben Chittick"
date: "3/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# adapted from https://rpubs.com/womeimingzi11/how_my_spotify_looks_like

#load packages
library(spotifyr)
library(tidyverse)
library(knitr)
library(ggplot2)

### Spotify Creds
Sys.setenv(SPOTIFY_CLIENT_ID = 'b665cb52a2e64fbaad682eb43fbb203c',
           SPOTIFY_CLIENT_SECRET = '83d0a0f785ff45adbf80668efad921f5')

### personal authorization code
get_spotify_authorization_code()
```


## Making sure you can pull from spotify api 
```{r}
### Data
beatles <- get_artist_audio_features('the beatles')
head(beatles)
```

# Favorite Tracks 
```{r}
all_my_fav_tracks <-

  ceiling(get_my_saved_tracks(include_meta_info = TRUE)[['total']] / 50) %>%
  seq() %>%
  map(function(x) {
    get_my_saved_tracks(limit = 50, offset = (x - 1) * 50)
  }) %>% reduce(rbind)


# Let's check the structure of our tracks.
glimpse(all_my_fav_tracks)
```

# All Artist from Favorite Tracks 
```{r}
artist_from_fav_tracks <-
  all_my_fav_tracks %>%
  select(track.artists) %>%
  reduce(rbind) %>%
  reduce(rbind) %>%
  # I don't think we need Urls in further analyses, id (unique mark of artist) and name are selected here.
  select(id, name)
```

# Number of Tracks by Artist 
```{r}
track_num_artist <-
  artist_from_fav_tracks %>%
  count(id, sort = TRUE) %>%
  left_join(artist_from_fav_tracks, by = 'id',.) %>%
  unique() %>%
  select(-id) %>%
  top_n(20, n) %>%
  arrange(-n)

track_num_artist  %>%
  kable()
```


```{r}
# For numerical variables, sometimes for simplifying problems, cut them into fractions is a good idea. Here, we go further, we fill the column plot with different color to represent different frequency group.
track_num_artist %>%
  mutate(
    freq = case_when(
      n > 100 ~ 'More than 100 tracks',
      between(n, 50, 99) ~ '50~99 tracks',
      between(n, 20, 49) ~ '20~49 tracks',
      TRUE ~ 'Less than 20 tracks'
    )
  ) %>%
  # To avoid mess up the order of frequency group, I always suggest to convert the category variables as factor variables, with built-in order, levels.
  mutate(freq = factor(
    freq,
    levels = c(
      'More than 100 tracks',
      '50~99 tracks',
      '20~49 tracks',
      'Less than 20 tracks'
    )
  )) %>%
  ggplot(mapping = aes(
    x = reorder(name, -n),
    y = n,
    fill = freq
  )) +
  geom_col() +
  labs(fill = NULL,title = 'Who is My Favorite Artist',caption = 'data from spotify via spotiyr') +
  xlab('Artist') +
  ylab('Tracks Number') +
  theme_classic() +
  theme(axis.text.x = element_text(angle = -60),
        axis.title = element_text(face = 'bold'),
        plot.title = element_text(hjust = 0.5, face = 'bold', size = 15),
        plot.caption = element_text(hjust = 1,face = 'bold.italic'))
```

# Get All Audio Features 
```{r}

audio.features = 
  track_num_artist$name %>%
    map(function(x){
      get_artist_audio_features(x)
      }) %>%
    reduce(rbind) %>%
    inner_join(all_my_fav_tracks,
               by = c('track_id' = 'track.id'))

```


summary(audio.features)
```{r}

ggplot(data = audio.features, aes(x = valence, y = energy, color = artist_name)) +
  geom_jitter() +
  geom_vline(xintercept = 0.5) +
  geom_hline(yintercept = 0.5) +
  scale_x_continuous(expand = c(0, 0), limits = c(0, 1)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1)) +
  annotate('text', 0.25 / 2, 0.95, label = "Turbulent/Angry", fontface =
             "bold") +
  annotate('text', 1.75 / 2, 0.95, label = "Happy/Joyful", fontface = "bold") +
  annotate('text', 1.75 / 2, 0.05, label = "Chill/Peaceful", fontface =
             "bold") +
  annotate('text', 0.25 / 2, 0.05, label = "Sad/Depressing", fontface =
             "bold")
```

